sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t remus95/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true remus95/docker-react npm run test -- --coverage