name: Auto build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker build -t remus95/docker-react -f Dockerfile.dev .
      with:
        context: ./
    - name: Run the Docker image
      run: docker run remus95/docker-react npm run test -- --coverage
